### ISSUE TITLE
Year of Plenty not playing

### ISSUE THREAD

**Issue by qzcx** [film42/cs340-catan#24] opened 2014-03-25 21:01 UTC
I saw a bug where year of plenty wouldn't send the server call. I refreshed and then I was able to use it. Just keep an eye out for something similar.

**Comment by junetang** [comment] 2014-03-25 21:07
if when play "year of Plenty", if "ore" resource is selected. the command "year of plenty" is not sent to server call. if other resources are selected. it is sent to the sever call.

**Comment by todoakaio** [comment] 2014-03-25 23:40
Marking as duplicate of #20

**Closed as completed by todoakaio** 2014-03-25 23:40 UTC
Labels: duplicate
